### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by ddl1001** [ddl1001/GESPRO_PracticaGestionTareas_2021#21]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by afp1002** [comment]
![d292d962-e621-11e6-915a-a39387803ce0](https://user-images.githubusercontent.com/74208893/100466985-134cd580-30d2-11eb-87f2-bce829762872.png)
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry
