### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by dgr1003** [ddl1001/GESPRO_PracticaGestionTareas_2021#25]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by afp1002** [comment]
![1](https://user-images.githubusercontent.com/74208893/100467898-9c184100-30d3-11eb-8d66-85310a13a529.jpg)
![2](https://user-images.githubusercontent.com/74208893/100467931-ae927a80-30d3-11eb-88d6-e2b3ceaa30bb.jpg)
![3](https://user-images.githubusercontent.com/74208893/100467942-b2260180-30d3-11eb-9b6d-955f97966cd9.jpg)
![4](https://user-images.githubusercontent.com/74208893/100467949-b6521f00-30d3-11eb-81e4-eccee4d717dc.jpg)
![5](https://user-images.githubusercontent.com/74208893/100467958-b94d0f80-30d3-11eb-9551-14e17bbc8b40.jpg)
![6](https://user-images.githubusercontent.com/74208893/100467964-bd792d00-30d3-11eb-9407-a77832c88dd4.jpg)
![7](https://user-images.githubusercontent.com/74208893/100467974-c10cb400-30d3-11eb-9f7d-07ca767726a8.jpg)

**Comment by dgr1003** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
